=== Mont3iro68/PRI-19-20-TPCs/TPC2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (header,team,abstract,deliverables) >
<!ELEMENT header (key_name,title,subtitle?,begin_date,end_date,supervisor) >
<!ELEMENT key_name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
                href CDATA #IMPLIED >
                
                
<!ELEMENT team (element+) >
<!ELEMENT element (#PCDATA) >
<!ELEMENT t_mail (#PCDATA) >
<!ATTLIST element 
               id ID #REQUIRED 
               mail CDATA #REQUIRED >


<!ELEMENT abstract (paragraph+) >
<!ELEMENT paragraph (#PCDATA|itallic|bold)* >
<!ELEMENT itallic (#PCDATA|bold)* >
<!ELEMENT bold (#PCDATA|itallic)* >
<!ELEMENT deliverables (items+) >
<!ELEMENT items (#PCDATA)>
<!ATTLIST items
             href CDATA #REQUIRED>

=== Mont3iro68/PRI-19-20-TPCs/TPC2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "file:/home/mont3iro/Documents/Universidade/PLC/PRI/PRI19-20TPCs/TPC2/pr.dtd">
<pr>
    <header>
        <key_name></key_name>
        <title></title>
        <begin_date></begin_date>
        <end_date></end_date>
        <supervisor href="http://www.di.uminho.pt/~jcr">Jos√© Carlos Ramalho</supervisor>
    </header>
    
    <team>
        <element id="A74036" mail="a74036@alunos.uminho.pt">Manuel Monteiro</element>
    </team>
    
    <abstract>
        <paragraph></paragraph>
    </abstract>
    <deliverables>
        <items href=""></items>
    </deliverables>
</pr>
